#!/bin/bash

readonly LOGIN_PAGE="http://englishharmony.com/secure/login"
readonly SESSION_COOKIE_NAME="amember_nr"

function usage
{
    echo "usage: $0 username password module lesson"
    echo "module = 1..4, lesson = 1..30"
}

# check arguments count:
if [ $# -ne 4 ]; then
    usage; exit 1
fi

username="$1"
password="$2"
module=$3
lesson=$4

# check arguments values:
if (( $module > 4 || $module < 1 || $lesson > 30 || $lesson < 1 )); then
    usage; exit 1
fi
if [[ -z $username || -z $password ]]; then
    usage; exit 1
fi

# login with the credentials and write cookies into the file:
curl -s -S -d "amember_login=$username&amember_pass=$password" -c cookies.txt $LOGIN_PAGE > /dev/null

# check login status
if cat cookies.txt | grep -q $SESSION_COOKIE_NAME; then
    echo "login succeed"
else
    echo "login failed"; exit 1
fi

# download lesson html page:
curl -b cookies.txt -O -s -S http://englishharmony.com/ehsystem/M$module/lesson$lesson.html > /dev/null

# extract a name to be given to swf file:
swf_name=$(perl -nle 'print $& if m{English Harmony System De Luxe Edition - \K[^<]+}' lesson$lesson.html).swf
# extract swf web address:
swf_address=$(perl -nle 'print $& if m{<param name="movie" value="\K[^"]+}' lesson$lesson.html)
# check swf_name, swf_address:
if [[ -z $swf_name || -z $swf_address ]]; then
    echo "something went wrong with extracting swf info from the website";
    echo "check contents of lesson$lesson.html"; exit 1
else
    # download swf file:
    curl -o "$swf_name" $swf_address;
    rm lesson$lesson.html
fi